server:
  port: 8761

spring:
  application:
    name: discovery-server
eureka:
  enviroment: default
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

