server:
  port: ${port:8761}

spring:
  application:
    name: discovery-server
eureka:
  enviroment: default
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://192.168.137.1:8761/eureka/
