server:
  port: 8084

spring:
  datasource:
    platform: postgresql
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/tyke-notifications
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-on-validation-error: false
  jpa:
    open-in-view: true
  application:
    name: notifications-service

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    routes:
      enabled: true
